Add atlasScheduledAutoscaling (SRE-720)
RocketChat/airlock pull request #18
Opened 2024-11-01 05:40 UTC by r0zbot

2024-11-01 05:53 UTC, debdutdeb commented on api/v1alpha1/mongodbcluster_types.go
> +	// +kubebuilder:validation:Enum=M0;M2;M5;M10;M20;M30;M40;M50;M60;M80;M140;M200;M300;M400;M500;M700;M900;M1000
should shared tiers be listed as valid scale downs or scale ups? likely we don't want to scale down so much or up, we could avoid mistakes like typos by not having them in validation.

2024-11-01 05:53 UTC, debdutdeb commented on api/v1alpha1/mongodbcluster_types.go
> +	ScaleDownExpression string `json:"scaleDownExpression,omitempty"`
```suggestion
	ScaleDownCronExpression string `json:"scaleDownCronExpression,omitempty"`
```

2024-11-01 05:54 UTC, debdutdeb commented on api/v1alpha1/mongodbcluster_types.go
> +	ScaleUpExpression string `json:"scaleUpExpression,omitempty"`
```suggestion
	ScaleUpCronExpression string `json:"scaleUpCronExpression,omitempty"`
```
being more verbose as expression can mean plain texts too.

2025-01-23 19:39 UTC, jcbrtl commented on controllers/mongodbcluster_controller.go
> +	if scheduledAutoscaling != nil && scheduledAutoscaling.Enabled {
Negate and return early instead

2025-01-23 20:03 UTC, jcbrtl commented on controllers/mongodbcluster_controller.go
> +			}
```suggestion
		if foundUp != nil && foundUp.Tags()[1] != scheduledAutoscaling.ScaleUpCronExpression+scheduledAutoscaling.HighTier {
			logger.Info("Removing outdated upscaling job for " + mongodbClusterCR.Name)

			err = r.Scheduler.RemoveJob(foundUp.ID())
			if err != nil {
				logger.Error(err, "Error removing outdated upscaling job")
				return err
			}
			
			foundUp = nil;
		}
		
		if foundUp == nil {
			// maybe call a func...
```

Can do similar for foundDown section

2025-01-24 09:48 UTC, debdutdeb requested changes
I have one more concern here - the cron expressions allow for anything to happen (not arguing against it, i like the flexibility).

but we almost always want to give it a time, not `scale up every 23 hours` or something.

problem here is that if airlock restarts, jobs are recreated, for any schedule that doesn't explicitly mention hour, the schedule will shift forward.

we can enforce it at review however, I think enforcing through app is better.

idk how to make sure it works. could be Field(expr)[1] == "*" then set event as invalid shcedule or breaking it in parts in crd.

2025-01-24 09:48 UTC, debdutdeb commented on config/crd/bases/airlock.cloud.rocket.chat_mongodbclusters.yaml
> +                    - M200
m10 as a high tier would be .. interesting :p

2025-01-24 09:48 UTC, debdutdeb commented on config/crd/bases/airlock.cloud.rocket.chat_mongodbclusters.yaml
> +                    - M200
m200 as low when :p

2025-01-24 09:48 UTC, debdutdeb commented on controllers/common.go
> +		if strings.Contains(cluster.SrvAddress, hostTemplate) {
can we use instead url.Parse() then Hostname() instead? this seems like a bug *can* occur if subdomain difference like smaller.

2025-01-24 09:48 UTC, debdutdeb commented on controllers/mongodbcluster_controller.go
> +		}
same early return here (as Julio said smwh else)

2025-01-24 09:48 UTC, debdutdeb commented on config/samples/airlock_v1alpha1_mongodbcluster.yaml
> +    scaleUpCronExpression: "0 0 * * *"
I love the word use of `cronexpression` over just `expression` - small +ve comment.

2025-01-24 09:48 UTC, debdutdeb commented on controllers/mongodbcluster_controller.go
> +		}
this `or` - if err is nil but second condition is true, what happens with logger.Error handling nil err? subsequently returning a nil err causing caller of this function to handle function completion errornously?

2025-01-24 09:48 UTC, debdutdeb commented on controllers/mongodbcluster_controller.go
> +							ScalingDownErrorGauge.WithLabelValues(mongodbClusterCR.Name).Inc()
same comment as above.

also, should the message here include err.Error() if it's non-nil? that way we know from describe what went wrong instead of jumping back to logs?

2025-01-24 13:23 UTC, jcbrtl commented on controllers/mongodbcluster_controller.go
> +		}
It is ok to use nil as logger arg (some clients won't error as request succeeded despite the http response code). But good catch on func not returning error when code != 200

2025-01-27 15:40 UTC, jcbrtl approved these changes
That's ok. Dream would be to scale using critical metrics, but we're learning and this is an acceptable step thinking on costs

2025-01-27 18:05 UTC, debdutdeb approved these changes

2025-01-27 18:12 UTC, merged